name: Continuous Integration
on:
  schedule:
    # weekdays only
    - cron: '0 16 * * 1-5'
  # update to schedule once tested
  push:

env:
  DESIRED_DOTNET_MAJOR_VERSION: 7

jobs:
  gitpod-image-check:
    name: Check the required tooling exists
    #TODO: update to use main branch once tested
    uses: CorndelWithSoftwire/DevOps-Course-Workflows/.github/workflows/docker-image-tooling-check.yml@d18b95ca27fbc400e8dbdded7ef3babecd8cc53a
    with:
      docker-image: gitpod/workspace-dotnet:latest
      tools-to-check: dotnet@7 node npm docker
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}